# Generated by Django 5.2.9 on 2025-12-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vendorcategory_options_vendor_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanningTask',
        ),
    ]
