# Generated by Django 5.2.9 on 2025-12-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_planningtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorimage',
            name='average_price',
            field=models.PositiveIntegerField(blank=True, help_text='Approx. average package price in INR', null=True),
        ),
    ]
