# Generated by Django 5.2.9 on 2025-12-03 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vendorimage_average_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorimage',
            name='average_price',
        ),
        migrations.AddField(
            model_name='vendor',
            name='average_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorimage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.vendor'),
        ),
    ]
