# Generated by Django 5.2.9 on 2025-12-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_vendorimage_average_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='preferred_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='theme_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
