# Generated by Django 5.2.9 on 2025-12-05 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactmessage_preferred_week_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('-rating', 'name')},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='price_level',
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='decor_price',
            field=models.PositiveIntegerField(default=0, help_text='Decor package price (Decor)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='makeup_price',
            field=models.PositiveIntegerField(default=0, help_text='Makeup package price (Makeup Artist)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='price_per_day',
            field=models.PositiveIntegerField(default=0, help_text='INR per day (Photography)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='price_per_plate',
            field=models.PositiveIntegerField(default=0, help_text='INR per plate (Catering)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='average_price',
            field=models.PositiveIntegerField(default=0, help_text='Average booking price (Venue)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.vendorcategory'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
