# Generated by Django 5.2.9 on 2025-12-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_vendor_options_remove_vendor_price_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='preferred_week',
            new_name='theme',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='theme_color',
            new_name='week',
        ),
    ]
