# Generated by Django 5.2.9 on 2025-12-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_preferred_week_contactmessage_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='vendor_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
