# Generated by Django 5.2.9 on 2025-12-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contactmessage_vendor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='theme',
            new_name='theme_color',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='preferred_week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
